### ISSUE TITLE
Compatibility with Redmine 5.0x

### ISSUE THREAD

**Issue by SinghNanak** [nanego/redmine_projects_queries_extension#1]

**Comment by dzzrit** [comment]
![企业微信截图_16894388015134](https://github.com/nanego/redmine_projects_queries_extension/assets/139627296/93135b91-79b8-4ea7-a20d-07e38ea407e2)

**Comment by nanego** [comment]
The plugin has been updated and is now compatible with Redmine 5.0
Please give it a try and let us know if you encounter any issues.
